### ISSUE TITLE
'DeviceTokenCredentials' is not assignable to type 'ServiceClientCredentials'

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Azure/ms-rest-nodeauth#67]
**Package Version**: 2.0.2
**nodejs version**: 10.16.0
**os name/version**: mac
**Describe the bug**

I'm trying to use latest of both `@azure/ms-rest-nodeauth` (2.0.2) and `@azure/ms-rest.js` (2.0.3), but the types don't match up.

```
Type 'DeviceTokenCredentials' is not assignable to type 'ServiceClientCredentials'.
  Types of property 'signRequest' are incompatible.
    Type '(webResource: import("/Users/erijiz/Repos/vscode-azuretools/ui/node_modules/@azure/ms-rest-nodeauth/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource) => Promise<...>' is not assignable to type '(webResource: import("/Users/erijiz/Repos/vscode-azuretools/ui/node_modules/@azure/ms-rest-azure-js/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource) => Promise<...>'.
      Types of parameters 'webResource' and 'webResource' are incompatible.
        Type 'import("/Users/erijiz/Repos/vscode-azuretools/ui/node_modules/@azure/ms-rest-azure-js/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource' is not assignable to type 'import("/Users/erijiz/Repos/vscode-azuretools/ui/node_modules/@azure/ms-rest-nodeauth/node_modules/@azure/ms-rest-js/es/lib/webResource").WebResource'.
          Types of property 'headers' are incompatible.
            Type 'import("/Users/erijiz/Repos/vscode-azuretools/ui/node_modules/@azure/ms-rest-azure-js/node_modules/@azure/ms-rest-js/es/lib/httpHeaders").HttpHeaders' is not assignable to type 'import("/Users/erijiz/Repos/vscode-azuretools/ui/node_modules/@azure/ms-rest-nodeauth/node_modules/@azure/ms-rest-js/es/lib/httpHeaders").HttpHeaders'.
              Types have separate declarations of a private property '_headersMap'.ts(2322)
```

Likely because this package is currently using `^1.8.7` for `@azure/ms-rest-js`. Can we get it updated to at least `^2.0.0`?

**Comment by amarzavery** [comment]
We will be releasing 3.0.0 version of ms-rest-nodeauth that depends on 2.x.x version of ms-rest-js shortly. This should fix the problem described in this issue and will also resolve #69 with fix provided in #70

**Comment by amarzavery** [comment]
Version 3.0.0 has been published. Please use that and let us know if that still causes issues.

**Comment by ruisilva450** [comment]
I don't think this is fixed at all.
When running:
```
msRestNodeAuth.interactiveLoginWithAuthResponse().then((authres) => {
  console.dir(authres, { depth: null });

  // Here you have a problem if you want to use any type 
  // of azure client because your authres is of type msRestNodeAuth.DeviceTokenCredentials
  const client = new SubscriptionClient(creds, subscriptionId); // <== this simply doesn't work

  client.operations.list().then((result) => {
    console.log("The result is:");
    console.log(result);
  });
}).catch((err) => {
  console.log(err);
});
```

This is an example for [arm-subscriptions](https://azure.github.io/azure-sdk-for-js/arm-subscriptions/index.html#how-to-use) but any other that I tried is the same thing.

Here you have the constructor of ```SubscriptionClient```:

```
class SubscriptionClient extends SubscriptionClientContext {
  // Operation groups
  operations: operations.Operations;
  subscriptionOperations: operations.SubscriptionOperations;
  subscriptionFactory: operations.SubscriptionFactory;
  subscriptions: operations.Subscriptions;
  tenants: operations.Tenants;

  /**
   * Initializes a new instance of the SubscriptionClient class.
   * @param credentials Credentials needed for the client to connect to Azure.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.SubscriptionClientOptions) {
    super(credentials, options);
    this.operations = new operations.Operations(this);
    this.subscriptionOperations = new operations.SubscriptionOperations(this);
    this.subscriptionFactory = new operations.SubscriptionFactory(this);
    this.subscriptions = new operations.Subscriptions(this);
    this.tenants = new operations.Tenants(this);
  }
}
```

Please, let us know if there are any other versions of this lib that doesn't bring this issue:

Here are the versions I use:
```
    "@azure/arm-apimanagement": "^5.1.0",
    "@azure/arm-storage": "^9.0.1",
    "@azure/arm-subscriptions": "^1.0.0",
    "@azure/ms-rest-js": "^2.0.4",
    "@azure/ms-rest-nodeauth": "^3.0.0"
```

**Comment by amarzavery** [comment]
@ruisilva450 - Please use `^2.0.4` version of `@azure/ms-rest-nodeauth`. That should fix the issue for now.


/cc @ramya-rao-a , @daviwil - Whenever we generate new versions of any JS package from now onwards either using the `4.2.x` version of `autorest.typescript` generator only then customers will be able to use `3.x.x` version of `@azure/ms-rest-nodeauth`. Otherwise, `2.0.4` version of `@azure/ms-rest-nodeauth` needs to be used for existing versions of packages that were generated using `~4.1.x` version of generator.

**Comment by jake-wickstrom-lb** [comment]
I am still having this issue when using `^2.0.4 `version of `@azure/ms-rest-nodeauth`

When  running the following code:

```
msRestAzure.loginWithServicePrincipalSecret(clientID, clientSecret, tenantID, function(err, credentials) {  
      if (err) return console.log(err);
      var client = new EventGridManagementClient(credentials, 'your-subscriptionId');
    });
})
```

I get the following error:

```
Argument of type 'ApplicationTokenCredentials' is not assignable to parameter of type ServiceClientCredentials'.
  Types of property 'signRequest' are incompatible.
    Type '(webResource: WebResource, callback: (err: Error) => void) => void' is not assignable to type '(webResource: WebResource) => Promise<WebResource>'.```

**Comment by ramya-rao-a** [comment]
@jake-wickstrom-lb Can you share the package name and version for Event Grids that you are using?

**Comment by jake-wickstrom-lb** [comment]
Did more digging into the problem, it seems the Event Grid and Event Grid Management packages are out of sync, so that when one does not throw this type error the other does. The versions I am currently using are:

    "@azure/arm-eventgrid": "4.2.0"
    "@azure/eventgrid": "1.5.0"

Currently arm-eventgrid is working, while eventgrid is throwing the error

**Comment by ramya-rao-a** [comment]
Thanks @jake-wickstrom-lb 
We can definitely have that fixed, can you please log an issue for the same at https://github.com/Azure/azure-sdk-for-js?

**Comment by felpel** [comment]
@jake-wickstrom-lb have you created the issue or were you able to fix this?

I am trying to migrate our existing project that uses multiples ARM packages previously found in Azure SDK for Node.js to the ones now listed in Azure SDK for JS.

**Comment by jake-wickstrom-lb** [comment]
@felpel https://github.com/Azure/azure-sdk-for-js/issues/6368
